title: bytebl33d
email:
description: >- # this means to ignore newlines until "baseurl:"
  Bytebl33d's Cyber Security Blog
github_username: bytebl33d
minimal_mistakes_skin: default
search: true
google_site_verification: "0_FOeRycTPlnDPidT1zXs_IJGABEZPWfvcpiAP"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0

permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "bytebl33d"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a software and security enthousiast striving to create innovative and secure software systems."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bytebl33d"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bytebl33d"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
